### ISSUE TITLE
Access the lyric data from an entire album

### ISSUE THREAD

**Issue by AlamarW** [johnwmillr/LyricsGenius#107]
I'm intending to use this to pull lyrics from an entire album but I don't see an easy way to go about doing it. I would be a great feature to be able to pull from albums specifically. Otherwise, I find that I have to go song by song in album order of the songs I'm looking to save for analysis.

**Comment by ExalFabu** [comment]
Hi, I also have the need of an album feature for a project I am working on so I tried reading the official API documentation by Genius and there was nothing useful, I later read on a [forum thread](https://genius.com/discussions/292589-Get-artists-album-list-and-albums-tracklist) that they decided to keep that part of the API closed to the public, so I analyzed the requests on their site and this is what I found out:
_You are not allowed to do any of this requests if you are using the session logged in via the client access token_

-  How to get all the album of an artist having their GeniusID
   - `requests.get('https://genius.com/api/artists/{ArtistID}/albums')`
   - Example on [pastebin](https://pastebin.com/tQWmPdsg)
- How to get the tracklist of an album having the name of the artist and the name of the album, using the previous request (if there are spaces I believe that you have to replace them with a -)
    - `requests.get("https://genius.com/api/page_data/album?page_path=%2Falbums%2F{ArtistName}%2F{AlbumName}")`
    - There's a ton of stuff in the response, the tracklist is under `response > page_data > album_appearences` 
    - Example on [pastebin](https://pastebin.com/4WL2zZiu)

This is all I found out and I think it's enough, since you also have the IDs of the songs once you get the tracklist.

**Comment by johnwmillr** [comment]
[Hugo Nattagh](https://github.com/Hugo-Nattagh/) was working on a fork for getting all the songs on album: https://github.com/Hugo-Nattagh/LyricsGenius

Take a look at his changes to see if it'd work for your purposes.

**Comment by Allerter** [comment]
> [Hugo Nattagh](https://github.com/Hugo-Nattagh/) was working on a fork for getting all the songs on album: https://github.com/Hugo-Nattagh/LyricsGenius
> 
> Take a look at his changes to see if it'd work for your purposes.

Why hasn't Hugo Nattagh's or ExalFabu's implementation of `search_album` become part of LyricsGenius yet?
