### ISSUE TITLE
Error Message: Specified song does not have a valid URL with lyrics. Rejecting.

### ISSUE THREAD

**Issue by ZeyPit** [johnwmillr/LyricsGenius#114]
Hi, John.

I'm trying to collect a corpus from lyrics of artists from a variety of genres.

I have one specific problem though. When I'm searching for any song with the code below:

`song = g.search_song('Work', artist='Rihanna')`

I'm getting this error: Specified song does not have a valid URL with lyrics. Rejecting.
Has this happened before? Any solutions?

**Version info**
 - Package version: 1.7.0
 - OS: Windows

**Comment by johnwmillr** [comment]
Hi @ZeyPit, do you still get this error when using the latest version of the package (`1.8.1`)? I am unable to reproduce this error.

John

**Comment by ZeyPit** [comment]
The error stopped occuring for no specific reason after a couple of days. Now it's working fine :)

**Comment by johnwmillr** [comment]
Great! Glad it’s working for you.

**Comment by ABSanthosh** [comment]
Hi, So the problem is that the api works fine some times and gives this issue randomly.

`
genius = lyricsgenius.Genius("<Valid key>")

song = genius.search_song("Earth", "Lil Dicky")
lyric_list = (song.lyrics)
`
I was able to get lyrics but after some time, it stops working and give this error:
`
Searching for "Earth" by Lil Dicky...
Specified song does not have a valid URL with lyrics. Rejecting.
Traceback (most recent call last):
  File "C:\Users\absan\Desktop\Python\2020 Projects\Project-Lypic\lypic1.py", line 23, in <module>
    lyric_list = (song.lyrics.replace("Chorus:","")).split()
AttributeError: 'NoneType' object has no attribute 'lyrics'
`
