### ISSUE TITLE
Assigning artists or lyrics to a variable

### ISSUE THREAD

**Issue by Aschinea** [johnwmillr/LyricsGenius#146]
Hello, I would like to add the songs that appear after using `artist = genius.search_artist(arg, max_songs=3, sort="title")` to variables, to make them more easy to manipulate and send seperately. 
Is there a way to do it? If yes, how? If not, it would be a really good idea to add it.

Also, when getting `artist.songs`, the string sent has the `[`, `(` and `'` characters on it, how can I remove them?

**Comment by Allerter** [comment]
Since `artist.songs` is a list, you can access the artist's songs by iterating over the list. I don't know if adding each song as an attribute to the Artist would be a good idea or even useful since you can easily iterate over the list and do whatever you want.
As for the second question, the `[`, `(` and `'` are there because you're printing a list object. You could do something like this:
```
for song in artist.songs:
    print(song.title, end=', ')
```

**Comment by johnwmillr** [comment]
Thank you, @Allerter!
