### ISSUE TITLE
search_artist returns wrong artist

### ISSUE THREAD

**Issue by kaiffeetasse** [johnwmillr/LyricsGenius#147]
**Describe the bug**
When searching for "Céline" the search_artist-Method returns "Celine Dion" although the search on genius.com returns the correct artist under "top result" (see: https://genius.com/search?q=C%C3%A9line)

**Expected behavior**
return https://genius.com/artists/Celine instead of https://genius.com/artists/Celine-dion

**To Reproduce**
`artist = genius.search_artist("Céline")`

`Searching for songs by Céline...`
`Changing artist name to 'Céline Dion'`

**Version info**
all versions

**Comment by Allerter** [comment]
Read the last paragraph for the solution.
When LyricsGenius performs a search to find the artist, it uses the method `search_genius_web`. Searching Genius web returns a dictionary that contains types like _top_hit_ and _artist_. Searching Genius web as the name suggests, is just like when an end-user performs a search on Genius. Usually, the top result is the correct one, but when LyricsGenius tries to match the artist name you provided to the artists in the results, it directly compares the two. If there is a match, the result will be returned, and if not, the first result is returned (which is usually the correct result, but not always).

In your case, your search term is "Céline" but the artist's name is "CÉLINE", and because of that the matching fails and the first result ("Céline Dion") is returned. You could either change your search term to "CÉLINE", or edit the code.
If you want to edit the code, change the following line in `api.py`:
```python
if hit['result'][result_type] == search_term:
```
to:
```python
if self._clean_str(hit['result'][result_type]) == self._clean_str(search_term):
```
