### ISSUE TITLE
set up as a pypi module?

### ISSUE THREAD

**Issue by Kyu** [johnwmillr/LyricsGenius#15]
If this is actually considered, this will require

- [x] adding a setup.py
- [x] moving config from config to inside python code

**Comment by Kyu** [comment]
I've actuakky never set up a pypi module before either, i just know pip needs a setup.py and that similar projects set up credentials in code  

using the example as an example, the goal would be to turn

```py
>>> import genius
>>> api = genius.Genius()
>>> artist = api.search_artist('Andy Shauf', max_songs=3)
```

into 

```py
>>> import genius
>>> api = genius.Genius(client_id='xyzzz', client_token='1235', client_secret='lalalalal')
>>> # or
>>> api = genius.Genius()
>>> api.id ='xyzzz'
>>> api.token = '12345'
>>> api.secret='lalalal'
>>> artist = api.search_artist('Andy Shauf', max_songs=3)

**Comment by johnwmillr** [comment]
Oh, gotcha. Yes, that shouldn't be too difficult a change to make (and would be a welcome one). From what I remember when I looked into the issue before, the actual process of adding the project to PyPi is a little more involved but is certainly doable. Go ahead and create a PR, I probably won't have time for it in the next few days.

**Comment by Kyu** [comment]
PR created in #17

**Comment by johnwmillr** [comment]
Resolved in #17.

**Comment by jakesherman** [comment]
Hi @johnwmillr,

I don't think this issue is resolved: while this repo is now formatted as a Python package, it is not yet submitted to PyPI. Basically, you can't install it just by doing `pip install genius_lyrics`. This seems like a really cool package, so it would be really neat to be able to install it from PyPI without having to clone this repo first.

Here is a great, simple tutorial for submitting your package to PyPI: http://peterdowns.com/posts/first-time-with-pypi.html. 

Note: There already is a geniuslyrics package on PyPI: https://pypi.python.org/pypi/geniuslyrics/0.1, not sure if you would need to change the name of this package?

Thanks,
Jake

**Comment by johnwmillr** [comment]
Hi @jakesherman!

You're right, I haven't yet gotten around to submitting the package to PyPI. And you're also right that it probably makes more sense to leave the issue open until it's actually available via `pip`. That's too bad about the name conflict... I'd prefer to not have to change mine, but that's probably not realistic.

I'm hoping to have the package on PyPI by this weekend. I'm glad you're interested in the project!

John

**Comment by johnwmillr** [comment]
Done! Thank you both for your help, @Kyu and @jakesherman. You should be able to [access the package on PyPI](https://pypi.python.org/pypi/lyricsgenius/0.2) now as well as through `pip install lyricsgenius`.

I decided to change the package name to `lyricsgenius` from `geniuslyrics` due to the name conflict.

I was also able to add command line functionality back in. Thanks for your help on that, @Kyu.

Let me know if `pip install lyricsgenius` doesn't work for you.

John

**Comment by jakesherman** [comment]
Awesome @johnwmillr, I am able to install it successfully with `pip install lyricsgenius`. Great package and blog post.

**Comment by johnwmillr** [comment]
Thank you for the motivation to actually resolve this issue!
