### ISSUE TITLE
Giving metadata instead of a lyrics

### ISSUE THREAD

**Issue by NIkitabala** [johnwmillr/LyricsGenius#151]
**Describe the bug**
Script gives HTML data in JSON file instead of actual lyrics.

**Expected behavior**
Lyrics, not HTML data shoud be saved in JSON file.

Here's code that I use:
```

import lyricsgenius
genius = lyricsgenius.Genius("#my_token")
artist = genius.search_artist("Пошлая Молли", max_songs=5, sort="title")
genius.remove_section_headers = True
print(artist.songs)
artist.save_lyrics()
```

When I tried to print lyrics of one song like:

```
song = genius.search_song("Show Must Go On", artist.name)
print(song.lyrics)

```
It gives this error: 'Nonetype' object has no attribute 'lyrics'.

**Comment by Allerter** [comment]
### How save_lyrics() works
When you use bare `save_lyrics()`, the _Artist_ object is saved in a JSON file that contains the artist's information beside the songs. To access the lyrics you would have to do this:
```python
import json
with open('file.json', 'r') as f:
    data = json.load(f)

for song in data['songs']:
    print(song.lyrics)
```
Or you could do `artist.save_lyrics(extension='txt')` to only have the lyrics saved.

### song.lyrics fails
Now on to why `song.lyrics` returns an error. Sometimes the library can't find the song and returns _None_ as a result. And a _Nonetype_ object has no attributes. If you want to see why the search failed, set `genius.verbose = True`. If you do that and get this: 
> Specified song does not contain lyrics. Rejecting.

It's because the library needs to be updated (see #148 for more info). I suggest looping over the search till you get the lyrics:
```python
while True:
    song = genius.search_song("Show Must Go On", artist.name)
    if song:
        break
```
Keep in mind that because of the bug I explained above, `artist.save_lyrics()` might save songs with empty lyrics for you. You could either wait for an update or fix the bug manually using the solution in #148.

**Comment by NIkitabala** [comment]
I found that one of the problems that final txt is not saved in UTF-8, so it doesn't work with Russian symbols. I'm currently looking how to make text file in this encoding, but can't find it.

**Comment by Allerter** [comment]
In this case, yes, the problem is with the encoding. If you set the `binary_encoding=True` for `artist.save_lyrics()`, it'll probably save the lyrics successfully, because the lyrics will get encoded in _utf8_.
```

**Comment by NIkitabala** [comment]
It works now with your solution, but still has problem like in #148. I guess, we should wait for fix.
