### ISSUE TITLE
Movie Script returned instead of Lyrics

### ISSUE THREAD

**Issue by jaidevshriram** [johnwmillr/LyricsGenius#192]
**Describe the bug**
Instead of returning a song, `search_song` returns a movie script/play.

**Expected behavior**
The function should return a valid song.

**To Reproduce**
Describe the steps required to reproduce the behavior.
1. Run `genius.search_song("Blue Jeans & A Boy's Shirt", "Glen Glenn")`
2. The Song item will have M Night Shyamalan as the Artist with a movie script in the lyrics.

The output can be seen [here](https://pastebin.com/XsgAQUEm).

**Version info**
 - Package version: 3.0.0
 - OS: Ubuntu 18.04.5

**Additional context**
Sometimes I also get a list of songs instead of a song's lyrics. The above example was just one instance, there are more examples.

**Comment by allerter** [comment]
Before getting to the actual issue, please note that the lyrics for that song are missing on Genius and even if the package found the song successfully, it would return None.
There are two reasons why this issue has occurred:
- The song you're looking for uses `and` instead of the `&` you provided. But even when I  use `and` it returns the same result (this happens for neither `&` nor `and` when using the browser - very strange).
- When the search fails and no matching item is found, the search returns the first song that has lyrics. That's why you're getting that song instead of the one you wanted. I improved the matching a bit just now, but your issue persists.

My suggestion is that if you find `search_song` to be unreliable, use the various [search methods](https://lyricsgenius.readthedocs.io/en/master/reference/genius.html#search-methods) available and do the matching yourself. After all, `search_song` is merely a convenience method.
