### ISSUE TITLE
Trouble with cyrillic

### ISSUE THREAD

**Issue by DiSonDS** [johnwmillr/LyricsGenius#21]
## TRY:

> import lyricsgenius as genius
> api = genius.Genius('token')
> song = api.search_song('Возможно')
> 
> print(song.lyrics)
> 

## Possible Solution:
**api.py**

> 110: lyrics = html.find("div", class_="lyrics").get_text().encode('ascii','ignore').decode('ascii')

change to

> 110: lyrics = html.find("div", class_="lyrics").get_text()

**Comment by johnwmillr** [comment]
Thanks for pointing this out! Are you using Python 2 or 3? The solution you've suggested works well for me for Python 3 but throws a `UnicodeEncodeError` in Python 2. From my understanding, Python 3 does a much better job of handling Unicode text than Python 2.

My `.encode('ascii','ignore').decode('ascii')` line is basically a kludge to try and deal with these `UnicodeEncodeError` errors; I hadn't encountered this issue for a while, but here's proof that my solution is inadequate.

Do you want to put together a pull request addressing this issue? I'd be happy to merge your changes if you're able to solve the issue for both Python 2 and 3. Otherwise I'll try to get to the issue once I have time.

John

**Comment by DiSonDS** [comment]
@johnwmillr I'm using Python 3 and I did not even think about Python 2. Hmm...

**Comment by johnwmillr** [comment]
Right, your solution is good for Python 3, but 2 is a pain... Maybe I need to think about whether it's worth supporting 2 much longer. It may make sense to allow Python 2 to just throw an error on the `UnicodeEncodeError` and let the Python 2 user deal with it as they like (as I mentioned in my comment on your PR).
