### ISSUE TITLE
Is it legal doing the scrapping of html pages with the lyrics?

### ISSUE THREAD

**Issue by acs** [johnwmillr/LyricsGenius#33]
Hi @johnwmillr!

Pretty cool work LyricsGenius but I have a doubt: is it legal to scrap the lyrics from Genius HTML pages? Reading in the support forums I have found:

https://genius.com/discussions/277279-Get-the-lyrics-of-a-song

What do you think? The safe approach for building web interfaces seems to be to just embed the genius viewer. But it is more flexible if you have direct access to the lyrics contents.

**Comment by johnwmillr** [comment]
Hi @acs!

Glad you found the project and thanks for reaching out.

Genius does mention scraping in their [terms of service](https://genius.com/static/terms), but I believe their intent is to prohibit the commercialization of their Intellectual Property. Their API provides access to pretty much all data on the website apart from lyrics. I assume Genius can't provide direct access to the lyrics due to the specifics of whatever licensing agreements they have with the third party providers.

Genius is well aware of the lyrics scrapers that exist on the web. I imagine they'll swoop in to shut them all down if they see the need. I have not, and have no intention of, commercializing or sharing the lyrics downloaded using `LyricsGenius`.

**Comment by acs** [comment]
Hi @johnwmillr,

Thank you very much. I was doing my [own research about the topic](https://github.com/acs/spoting/issues/5), also reading the terms of service, and my decision is to use scrapping when the use case does not have a web interface. If the use case has a web interface, probably I will include the genius html viewer including it in the web app if the user experience is good.

I have no intention neither to commercialize or distribute the lyrics.

I am working in the integration of a Spotify playlists tracks with their lyrics. It is a personal need I would love to cover. Let's see how far I can go! I will evalute the use of  `LyricsGenius` during the development.

Really cool stuff what you are doing at: http://www.johnwmillr.com/trucks-and-beer/.

Closing this question!!
