### ISSUE TITLE
Song.save_lyrics doesn't include song title in default file name

### ISSUE THREAD

**Issue by johnwmillr** [johnwmillr/LyricsGenius#80]
**Describe the bug**
The `Song.save_lyrics` method saves a file name with artist name but not song title, potentially overwriting different songs by the same artist.

**Expected behavior**
Default file name should be `f"Lyrics_{song.title}_{song.artist}.txt"`.

**To Reproduce**
Describe the steps required to reproduce the behavior.
1. `song = api.search_song("99 problems Jay-z")`
2. `song.save_lyrics()`

**Additional context**
Problem is an issue if saving multiple songs individually, potentially by the same artist. I should provide a `save_songs` method that accepts a list of songs.

**Comment by VitoMinheere** [comment]
I would like to pick up this task. 

However, changing the filename to include the song title is not the whole issue. 
Now there are 2 functions which save the lyrics, one for the song class and one for the artist class.

Ideally there would be only one functions. Perhaps the song.save_lyrics() can be written as to also be called with a list or dictionary so that the artist class can call the save_lyrics on all the songs for that artist.

**Comment by johnwmillr** [comment]
That'd be great if you could help out! I've [neglected](https://github.com/johnwmillr/LyricsGenius/blob/41f446c0c19882f5a1b695a151b07c623c3e8581/lyricsgenius/song.py#L84) the duplicate `save_lyrics()` functions for a while now. If you fix this "default file name" issue while addressing the larger issue of duplicated functions, that'd be ideal.

**Comment by johnwmillr** [comment]
Resolved by #84
