### ISSUE TITLE
Hi, I'm new to Python. Do you have any idea what this error might mean?

### ISSUE THREAD

**Issue by johnwmillr** [johnwmillr/LyricsGenius#85]
Hi, I'm new to Python. Do you have any idea what this error might mean? 

TypeError: 'NoneType' object is not subscriptable

_Originally posted by @raunakdaga in https://github.com/johnwmillr/LyricsGenius/issues/55#issuecomment-466425804_

**Comment by johnwmillr** [comment]
Hi @raunakdaga,

I'll need more context for the error before I can help you. What code did you run to produce this error?

**Comment by raunakdaga** [comment]
Hi,

I believe it had something to do with my installation. I reinstalled and I'm now unable to reproduce the error. I've been searching around this package because I want to use it at an upcoming hackathon and I haven't found any documentation. Is this something that is being worked on or that I could possibly assist with?

**Comment by johnwmillr** [comment]
Yes, if you'd like to contribute documentation you may open a PR. Some of the methods are already commented / documented, so you should follow the same style where other documentation is needed.

**Comment by johnwmillr** [comment]
Closing this issue as the `NoneType` issue appears to be resolved.
